package com.bilibala.manage.dao.mapper;

import com.bilibala.manage.dao.model.SysConf;
import com.bilibala.manage.dao.model.SysConfExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysConfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    int countByExample(SysConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    int deleteByExample(SysConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String sysKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    int insert(SysConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    int insertSelective(SysConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    List<SysConf> selectByExample(SysConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    SysConf selectByPrimaryKey(String sysKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysConf record, @Param("example") SysConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysConf record, @Param("example") SysConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysConf record);
}