package com.bilibala.manage.dao.mapper;

import com.bilibala.manage.dao.model.SysFunc;
import com.bilibala.manage.dao.model.SysFuncExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysFuncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func
     *
     * @mbggenerated
     */
    int countByExample(SysFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func
     *
     * @mbggenerated
     */
    int deleteByExample(SysFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer funcid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func
     *
     * @mbggenerated
     */
    int insert(SysFunc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func
     *
     * @mbggenerated
     */
    int insertSelective(SysFunc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func
     *
     * @mbggenerated
     */
    List<SysFunc> selectByExample(SysFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func
     *
     * @mbggenerated
     */
    SysFunc selectByPrimaryKey(Integer funcid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysFunc record, @Param("example") SysFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysFunc record, @Param("example") SysFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysFunc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysFunc record);
}