package com.bilibala.manage.dao.mapper;

import com.bilibala.manage.dao.model.SysFuncUrl;
import com.bilibala.manage.dao.model.SysFuncUrlExample;
import com.bilibala.manage.dao.model.SysFuncUrlKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysFuncUrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_url
     *
     * @mbggenerated
     */
    int countByExample(SysFuncUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_url
     *
     * @mbggenerated
     */
    int deleteByExample(SysFuncUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_url
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SysFuncUrlKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_url
     *
     * @mbggenerated
     */
    int insert(SysFuncUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_url
     *
     * @mbggenerated
     */
    int insertSelective(SysFuncUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_url
     *
     * @mbggenerated
     */
    List<SysFuncUrl> selectByExample(SysFuncUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_url
     *
     * @mbggenerated
     */
    SysFuncUrl selectByPrimaryKey(SysFuncUrlKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_url
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysFuncUrl record, @Param("example") SysFuncUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_url
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysFuncUrl record, @Param("example") SysFuncUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_url
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysFuncUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_url
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysFuncUrl record);
}