package com.bilibala.manage.dao.mapper;

import com.bilibala.manage.dao.model.SysLogOper;
import com.bilibala.manage.dao.model.SysLogOperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysLogOperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_oper
     *
     * @mbggenerated
     */
    int countByExample(SysLogOperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_oper
     *
     * @mbggenerated
     */
    int deleteByExample(SysLogOperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_oper
     *
     * @mbggenerated
     */
    int insert(SysLogOper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_oper
     *
     * @mbggenerated
     */
    int insertSelective(SysLogOper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_oper
     *
     * @mbggenerated
     */
    List<SysLogOper> selectByExample(SysLogOperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_oper
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysLogOper record, @Param("example") SysLogOperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_oper
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysLogOper record, @Param("example") SysLogOperExample example);
}