package com.bilibala.manage.dao.mapper;

import com.bilibala.manage.dao.model.SysOperate;
import com.bilibala.manage.dao.model.SysOperateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysOperateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operate
     *
     * @mbggenerated
     */
    int countByExample(SysOperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operate
     *
     * @mbggenerated
     */
    int deleteByExample(SysOperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operate
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer operid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operate
     *
     * @mbggenerated
     */
    int insert(SysOperate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operate
     *
     * @mbggenerated
     */
    int insertSelective(SysOperate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operate
     *
     * @mbggenerated
     */
    List<SysOperate> selectByExample(SysOperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operate
     *
     * @mbggenerated
     */
    SysOperate selectByPrimaryKey(Integer operid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operate
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysOperate record, @Param("example") SysOperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operate
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysOperate record, @Param("example") SysOperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operate
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysOperate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operate
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysOperate record);
}