package com.bilibala.manage.dao.mapper;

import com.bilibala.manage.dao.model.WxAccount;
import com.bilibala.manage.dao.model.WxAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbggenerated
     */
    int countByExample(WxAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbggenerated
     */
    int deleteByExample(WxAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbggenerated
     */
    int insert(WxAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbggenerated
     */
    int insertSelective(WxAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbggenerated
     */
    List<WxAccount> selectByExample(WxAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbggenerated
     */
    WxAccount selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WxAccount record, @Param("example") WxAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WxAccount record, @Param("example") WxAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WxAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WxAccount record);
}