package com.bilibala.manage.dao.mapper;

import com.bilibala.manage.dao.model.WxModule;
import com.bilibala.manage.dao.model.WxModuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    int countByExample(WxModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    int deleteByExample(WxModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String moduleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    int insert(WxModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    int insertSelective(WxModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    List<WxModule> selectByExample(WxModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    WxModule selectByPrimaryKey(String moduleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WxModule record, @Param("example") WxModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WxModule record, @Param("example") WxModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WxModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WxModule record);
}