package com.bilibala.manage.dao.model;

import java.util.ArrayList;
import java.util.List;

public class SysConfExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    public SysConfExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSysKeyIsNull() {
            addCriterion("SYS_KEY is null");
            return (Criteria) this;
        }

        public Criteria andSysKeyIsNotNull() {
            addCriterion("SYS_KEY is not null");
            return (Criteria) this;
        }

        public Criteria andSysKeyEqualTo(String value) {
            addCriterion("SYS_KEY =", value, "sysKey");
            return (Criteria) this;
        }

        public Criteria andSysKeyNotEqualTo(String value) {
            addCriterion("SYS_KEY <>", value, "sysKey");
            return (Criteria) this;
        }

        public Criteria andSysKeyGreaterThan(String value) {
            addCriterion("SYS_KEY >", value, "sysKey");
            return (Criteria) this;
        }

        public Criteria andSysKeyGreaterThanOrEqualTo(String value) {
            addCriterion("SYS_KEY >=", value, "sysKey");
            return (Criteria) this;
        }

        public Criteria andSysKeyLessThan(String value) {
            addCriterion("SYS_KEY <", value, "sysKey");
            return (Criteria) this;
        }

        public Criteria andSysKeyLessThanOrEqualTo(String value) {
            addCriterion("SYS_KEY <=", value, "sysKey");
            return (Criteria) this;
        }

        public Criteria andSysKeyLike(String value) {
            addCriterion("SYS_KEY like", value, "sysKey");
            return (Criteria) this;
        }

        public Criteria andSysKeyNotLike(String value) {
            addCriterion("SYS_KEY not like", value, "sysKey");
            return (Criteria) this;
        }

        public Criteria andSysKeyIn(List<String> values) {
            addCriterion("SYS_KEY in", values, "sysKey");
            return (Criteria) this;
        }

        public Criteria andSysKeyNotIn(List<String> values) {
            addCriterion("SYS_KEY not in", values, "sysKey");
            return (Criteria) this;
        }

        public Criteria andSysKeyBetween(String value1, String value2) {
            addCriterion("SYS_KEY between", value1, value2, "sysKey");
            return (Criteria) this;
        }

        public Criteria andSysKeyNotBetween(String value1, String value2) {
            addCriterion("SYS_KEY not between", value1, value2, "sysKey");
            return (Criteria) this;
        }

        public Criteria andSysValueIsNull() {
            addCriterion("SYS_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andSysValueIsNotNull() {
            addCriterion("SYS_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andSysValueEqualTo(String value) {
            addCriterion("SYS_VALUE =", value, "sysValue");
            return (Criteria) this;
        }

        public Criteria andSysValueNotEqualTo(String value) {
            addCriterion("SYS_VALUE <>", value, "sysValue");
            return (Criteria) this;
        }

        public Criteria andSysValueGreaterThan(String value) {
            addCriterion("SYS_VALUE >", value, "sysValue");
            return (Criteria) this;
        }

        public Criteria andSysValueGreaterThanOrEqualTo(String value) {
            addCriterion("SYS_VALUE >=", value, "sysValue");
            return (Criteria) this;
        }

        public Criteria andSysValueLessThan(String value) {
            addCriterion("SYS_VALUE <", value, "sysValue");
            return (Criteria) this;
        }

        public Criteria andSysValueLessThanOrEqualTo(String value) {
            addCriterion("SYS_VALUE <=", value, "sysValue");
            return (Criteria) this;
        }

        public Criteria andSysValueLike(String value) {
            addCriterion("SYS_VALUE like", value, "sysValue");
            return (Criteria) this;
        }

        public Criteria andSysValueNotLike(String value) {
            addCriterion("SYS_VALUE not like", value, "sysValue");
            return (Criteria) this;
        }

        public Criteria andSysValueIn(List<String> values) {
            addCriterion("SYS_VALUE in", values, "sysValue");
            return (Criteria) this;
        }

        public Criteria andSysValueNotIn(List<String> values) {
            addCriterion("SYS_VALUE not in", values, "sysValue");
            return (Criteria) this;
        }

        public Criteria andSysValueBetween(String value1, String value2) {
            addCriterion("SYS_VALUE between", value1, value2, "sysValue");
            return (Criteria) this;
        }

        public Criteria andSysValueNotBetween(String value1, String value2) {
            addCriterion("SYS_VALUE not between", value1, value2, "sysValue");
            return (Criteria) this;
        }

        public Criteria andSysDescIsNull() {
            addCriterion("SYS_DESC is null");
            return (Criteria) this;
        }

        public Criteria andSysDescIsNotNull() {
            addCriterion("SYS_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andSysDescEqualTo(String value) {
            addCriterion("SYS_DESC =", value, "sysDesc");
            return (Criteria) this;
        }

        public Criteria andSysDescNotEqualTo(String value) {
            addCriterion("SYS_DESC <>", value, "sysDesc");
            return (Criteria) this;
        }

        public Criteria andSysDescGreaterThan(String value) {
            addCriterion("SYS_DESC >", value, "sysDesc");
            return (Criteria) this;
        }

        public Criteria andSysDescGreaterThanOrEqualTo(String value) {
            addCriterion("SYS_DESC >=", value, "sysDesc");
            return (Criteria) this;
        }

        public Criteria andSysDescLessThan(String value) {
            addCriterion("SYS_DESC <", value, "sysDesc");
            return (Criteria) this;
        }

        public Criteria andSysDescLessThanOrEqualTo(String value) {
            addCriterion("SYS_DESC <=", value, "sysDesc");
            return (Criteria) this;
        }

        public Criteria andSysDescLike(String value) {
            addCriterion("SYS_DESC like", value, "sysDesc");
            return (Criteria) this;
        }

        public Criteria andSysDescNotLike(String value) {
            addCriterion("SYS_DESC not like", value, "sysDesc");
            return (Criteria) this;
        }

        public Criteria andSysDescIn(List<String> values) {
            addCriterion("SYS_DESC in", values, "sysDesc");
            return (Criteria) this;
        }

        public Criteria andSysDescNotIn(List<String> values) {
            addCriterion("SYS_DESC not in", values, "sysDesc");
            return (Criteria) this;
        }

        public Criteria andSysDescBetween(String value1, String value2) {
            addCriterion("SYS_DESC between", value1, value2, "sysDesc");
            return (Criteria) this;
        }

        public Criteria andSysDescNotBetween(String value1, String value2) {
            addCriterion("SYS_DESC not between", value1, value2, "sysDesc");
            return (Criteria) this;
        }

        public Criteria andSysSortIsNull() {
            addCriterion("SYS_SORT is null");
            return (Criteria) this;
        }

        public Criteria andSysSortIsNotNull() {
            addCriterion("SYS_SORT is not null");
            return (Criteria) this;
        }

        public Criteria andSysSortEqualTo(Integer value) {
            addCriterion("SYS_SORT =", value, "sysSort");
            return (Criteria) this;
        }

        public Criteria andSysSortNotEqualTo(Integer value) {
            addCriterion("SYS_SORT <>", value, "sysSort");
            return (Criteria) this;
        }

        public Criteria andSysSortGreaterThan(Integer value) {
            addCriterion("SYS_SORT >", value, "sysSort");
            return (Criteria) this;
        }

        public Criteria andSysSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("SYS_SORT >=", value, "sysSort");
            return (Criteria) this;
        }

        public Criteria andSysSortLessThan(Integer value) {
            addCriterion("SYS_SORT <", value, "sysSort");
            return (Criteria) this;
        }

        public Criteria andSysSortLessThanOrEqualTo(Integer value) {
            addCriterion("SYS_SORT <=", value, "sysSort");
            return (Criteria) this;
        }

        public Criteria andSysSortIn(List<Integer> values) {
            addCriterion("SYS_SORT in", values, "sysSort");
            return (Criteria) this;
        }

        public Criteria andSysSortNotIn(List<Integer> values) {
            addCriterion("SYS_SORT not in", values, "sysSort");
            return (Criteria) this;
        }

        public Criteria andSysSortBetween(Integer value1, Integer value2) {
            addCriterion("SYS_SORT between", value1, value2, "sysSort");
            return (Criteria) this;
        }

        public Criteria andSysSortNotBetween(Integer value1, Integer value2) {
            addCriterion("SYS_SORT not between", value1, value2, "sysSort");
            return (Criteria) this;
        }

        public Criteria andSysFlagIsNull() {
            addCriterion("SYS_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andSysFlagIsNotNull() {
            addCriterion("SYS_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andSysFlagEqualTo(Integer value) {
            addCriterion("SYS_FLAG =", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagNotEqualTo(Integer value) {
            addCriterion("SYS_FLAG <>", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagGreaterThan(Integer value) {
            addCriterion("SYS_FLAG >", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("SYS_FLAG >=", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagLessThan(Integer value) {
            addCriterion("SYS_FLAG <", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagLessThanOrEqualTo(Integer value) {
            addCriterion("SYS_FLAG <=", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagIn(List<Integer> values) {
            addCriterion("SYS_FLAG in", values, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagNotIn(List<Integer> values) {
            addCriterion("SYS_FLAG not in", values, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagBetween(Integer value1, Integer value2) {
            addCriterion("SYS_FLAG between", value1, value2, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("SYS_FLAG not between", value1, value2, "sysFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_conf
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_conf
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}