package com.bilibala.manage.dao.model;

public class SysConf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_conf.SYS_KEY
     *
     * @mbggenerated
     */
    private String sysKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_conf.SYS_VALUE
     *
     * @mbggenerated
     */
    private String sysValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_conf.SYS_DESC
     *
     * @mbggenerated
     */
    private String sysDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_conf.SYS_SORT
     *
     * @mbggenerated
     */
    private Integer sysSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_conf.SYS_FLAG
     *
     * @mbggenerated
     */
    private Integer sysFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_conf.SYS_KEY
     *
     * @return the value of sys_conf.SYS_KEY
     *
     * @mbggenerated
     */
    public String getSysKey() {
        return sysKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_conf.SYS_KEY
     *
     * @param sysKey the value for sys_conf.SYS_KEY
     *
     * @mbggenerated
     */
    public void setSysKey(String sysKey) {
        this.sysKey = sysKey == null ? null : sysKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_conf.SYS_VALUE
     *
     * @return the value of sys_conf.SYS_VALUE
     *
     * @mbggenerated
     */
    public String getSysValue() {
        return sysValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_conf.SYS_VALUE
     *
     * @param sysValue the value for sys_conf.SYS_VALUE
     *
     * @mbggenerated
     */
    public void setSysValue(String sysValue) {
        this.sysValue = sysValue == null ? null : sysValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_conf.SYS_DESC
     *
     * @return the value of sys_conf.SYS_DESC
     *
     * @mbggenerated
     */
    public String getSysDesc() {
        return sysDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_conf.SYS_DESC
     *
     * @param sysDesc the value for sys_conf.SYS_DESC
     *
     * @mbggenerated
     */
    public void setSysDesc(String sysDesc) {
        this.sysDesc = sysDesc == null ? null : sysDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_conf.SYS_SORT
     *
     * @return the value of sys_conf.SYS_SORT
     *
     * @mbggenerated
     */
    public Integer getSysSort() {
        return sysSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_conf.SYS_SORT
     *
     * @param sysSort the value for sys_conf.SYS_SORT
     *
     * @mbggenerated
     */
    public void setSysSort(Integer sysSort) {
        this.sysSort = sysSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_conf.SYS_FLAG
     *
     * @return the value of sys_conf.SYS_FLAG
     *
     * @mbggenerated
     */
    public Integer getSysFlag() {
        return sysFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_conf.SYS_FLAG
     *
     * @param sysFlag the value for sys_conf.SYS_FLAG
     *
     * @mbggenerated
     */
    public void setSysFlag(Integer sysFlag) {
        this.sysFlag = sysFlag;
    }
}