package com.bilibala.manage.dao.model;

public class SysFuncUrl extends SysFuncUrlKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func_url.DISABLE
     *
     * @mbggenerated
     */
    private Integer disable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func_url.DISABLE
     *
     * @return the value of sys_func_url.DISABLE
     *
     * @mbggenerated
     */
    public Integer getDisable() {
        return disable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func_url.DISABLE
     *
     * @param disable the value for sys_func_url.DISABLE
     *
     * @mbggenerated
     */
    public void setDisable(Integer disable) {
        this.disable = disable;
    }
}