package com.bilibala.manage.dao.model;

public class SysFunc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func.FUNCID
     *
     * @mbggenerated
     */
    private Integer funcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func.MENUID
     *
     * @mbggenerated
     */
    private Integer menuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func.OPERID
     *
     * @mbggenerated
     */
    private Integer operid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func.FUNCID
     *
     * @return the value of sys_func.FUNCID
     *
     * @mbggenerated
     */
    public Integer getFuncid() {
        return funcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func.FUNCID
     *
     * @param funcid the value for sys_func.FUNCID
     *
     * @mbggenerated
     */
    public void setFuncid(Integer funcid) {
        this.funcid = funcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func.MENUID
     *
     * @return the value of sys_func.MENUID
     *
     * @mbggenerated
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func.MENUID
     *
     * @param menuid the value for sys_func.MENUID
     *
     * @mbggenerated
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func.OPERID
     *
     * @return the value of sys_func.OPERID
     *
     * @mbggenerated
     */
    public Integer getOperid() {
        return operid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func.OPERID
     *
     * @param operid the value for sys_func.OPERID
     *
     * @mbggenerated
     */
    public void setOperid(Integer operid) {
        this.operid = operid;
    }
}