package com.bilibala.manage.dao.model;

public class SysFuncUrlKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func_url.FUNCID
     *
     * @mbggenerated
     */
    private Integer funcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func_url.URLID
     *
     * @mbggenerated
     */
    private Integer urlid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func_url.FUNCID
     *
     * @return the value of sys_func_url.FUNCID
     *
     * @mbggenerated
     */
    public Integer getFuncid() {
        return funcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func_url.FUNCID
     *
     * @param funcid the value for sys_func_url.FUNCID
     *
     * @mbggenerated
     */
    public void setFuncid(Integer funcid) {
        this.funcid = funcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func_url.URLID
     *
     * @return the value of sys_func_url.URLID
     *
     * @mbggenerated
     */
    public Integer getUrlid() {
        return urlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func_url.URLID
     *
     * @param urlid the value for sys_func_url.URLID
     *
     * @mbggenerated
     */
    public void setUrlid(Integer urlid) {
        this.urlid = urlid;
    }
}