package com.bilibala.manage.dao.model;

import java.util.Date;

public class SysLogOper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log_oper.USERID
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log_oper.USERNAME
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log_oper.operid
     *
     * @mbggenerated
     */
    private Integer operid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log_oper.OPERNAME
     *
     * @mbggenerated
     */
    private String opername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log_oper.PARAMS
     *
     * @mbggenerated
     */
    private String params;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log_oper.SUCCESS
     *
     * @mbggenerated
     */
    private Integer success;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log_oper.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log_oper.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log_oper.USERID
     *
     * @return the value of sys_log_oper.USERID
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log_oper.USERID
     *
     * @param userid the value for sys_log_oper.USERID
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log_oper.USERNAME
     *
     * @return the value of sys_log_oper.USERNAME
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log_oper.USERNAME
     *
     * @param username the value for sys_log_oper.USERNAME
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log_oper.operid
     *
     * @return the value of sys_log_oper.operid
     *
     * @mbggenerated
     */
    public Integer getOperid() {
        return operid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log_oper.operid
     *
     * @param operid the value for sys_log_oper.operid
     *
     * @mbggenerated
     */
    public void setOperid(Integer operid) {
        this.operid = operid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log_oper.OPERNAME
     *
     * @return the value of sys_log_oper.OPERNAME
     *
     * @mbggenerated
     */
    public String getOpername() {
        return opername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log_oper.OPERNAME
     *
     * @param opername the value for sys_log_oper.OPERNAME
     *
     * @mbggenerated
     */
    public void setOpername(String opername) {
        this.opername = opername == null ? null : opername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log_oper.PARAMS
     *
     * @return the value of sys_log_oper.PARAMS
     *
     * @mbggenerated
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log_oper.PARAMS
     *
     * @param params the value for sys_log_oper.PARAMS
     *
     * @mbggenerated
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log_oper.SUCCESS
     *
     * @return the value of sys_log_oper.SUCCESS
     *
     * @mbggenerated
     */
    public Integer getSuccess() {
        return success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log_oper.SUCCESS
     *
     * @param success the value for sys_log_oper.SUCCESS
     *
     * @mbggenerated
     */
    public void setSuccess(Integer success) {
        this.success = success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log_oper.REMARK
     *
     * @return the value of sys_log_oper.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log_oper.REMARK
     *
     * @param remark the value for sys_log_oper.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log_oper.CREATE_TIME
     *
     * @return the value of sys_log_oper.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log_oper.CREATE_TIME
     *
     * @param createTime the value for sys_log_oper.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}