package com.bilibala.manage.dao.model;

import java.util.ArrayList;
import java.util.List;

public class SysMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.MENUID
     *
     * @mbggenerated
     */
    private Integer menuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.PARENTID
     *
     * @mbggenerated
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.MENUITEM
     *
     * @mbggenerated
     */
    private String menuitem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.SORT
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.URL
     *
     * @mbggenerated
     */
    private String url;

    private List<SysMenu> childMenu;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.MENUID
     *
     * @return the value of sys_menu.MENUID
     *
     * @mbggenerated
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.MENUID
     *
     * @param menuid the value for sys_menu.MENUID
     *
     * @mbggenerated
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.PARENTID
     *
     * @return the value of sys_menu.PARENTID
     *
     * @mbggenerated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.PARENTID
     *
     * @param parentid the value for sys_menu.PARENTID
     *
     * @mbggenerated
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.MENUITEM
     *
     * @return the value of sys_menu.MENUITEM
     *
     * @mbggenerated
     */
    public String getMenuitem() {
        return menuitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.MENUITEM
     *
     * @param menuitem the value for sys_menu.MENUITEM
     *
     * @mbggenerated
     */
    public void setMenuitem(String menuitem) {
        this.menuitem = menuitem == null ? null : menuitem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.SORT
     *
     * @return the value of sys_menu.SORT
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.SORT
     *
     * @param sort the value for sys_menu.SORT
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.URL
     *
     * @return the value of sys_menu.URL
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.URL
     *
     * @param url the value for sys_menu.URL
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

	public List<SysMenu> getChildMenu() {
		return childMenu;
	}

	public void setChildMenu(List<SysMenu> childMenu) {
		this.childMenu = childMenu;
	}
    
	public void addChiledMenu(SysMenu menu){
		if(childMenu==null){
			childMenu = new ArrayList<SysMenu>();
		}
		childMenu.add(menu);
	}
}