package com.bilibala.manage.dao.model;

public class SysOperate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operate.OPERID
     *
     * @mbggenerated
     */
    private Integer operid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operate.OPERNAME
     *
     * @mbggenerated
     */
    private String opername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operate.OPERKEY
     *
     * @mbggenerated
     */
    private String operkey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operate.OPERID
     *
     * @return the value of sys_operate.OPERID
     *
     * @mbggenerated
     */
    public Integer getOperid() {
        return operid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operate.OPERID
     *
     * @param operid the value for sys_operate.OPERID
     *
     * @mbggenerated
     */
    public void setOperid(Integer operid) {
        this.operid = operid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operate.OPERNAME
     *
     * @return the value of sys_operate.OPERNAME
     *
     * @mbggenerated
     */
    public String getOpername() {
        return opername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operate.OPERNAME
     *
     * @param opername the value for sys_operate.OPERNAME
     *
     * @mbggenerated
     */
    public void setOpername(String opername) {
        this.opername = opername == null ? null : opername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operate.OPERKEY
     *
     * @return the value of sys_operate.OPERKEY
     *
     * @mbggenerated
     */
    public String getOperkey() {
        return operkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operate.OPERKEY
     *
     * @param operkey the value for sys_operate.OPERKEY
     *
     * @mbggenerated
     */
    public void setOperkey(String operkey) {
        this.operkey = operkey == null ? null : operkey.trim();
    }
}