package com.bilibala.manage.dao.model;

public class SysRoleFuncKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_func.FUNCID
     *
     * @mbggenerated
     */
    private Integer funcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_func.ROLEID
     *
     * @mbggenerated
     */
    private Integer roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_func.FUNCID
     *
     * @return the value of sys_role_func.FUNCID
     *
     * @mbggenerated
     */
    public Integer getFuncid() {
        return funcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_func.FUNCID
     *
     * @param funcid the value for sys_role_func.FUNCID
     *
     * @mbggenerated
     */
    public void setFuncid(Integer funcid) {
        this.funcid = funcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_func.ROLEID
     *
     * @return the value of sys_role_func.ROLEID
     *
     * @mbggenerated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_func.ROLEID
     *
     * @param roleid the value for sys_role_func.ROLEID
     *
     * @mbggenerated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}