package com.bilibala.manage.dao.model;

public class SysRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.ROLEID
     *
     * @mbggenerated
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.ROLENAME
     *
     * @mbggenerated
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.DISABLE
     *
     * @mbggenerated
     */
    private Integer disable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.ROLEID
     *
     * @return the value of sys_role.ROLEID
     *
     * @mbggenerated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.ROLEID
     *
     * @param roleid the value for sys_role.ROLEID
     *
     * @mbggenerated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.ROLENAME
     *
     * @return the value of sys_role.ROLENAME
     *
     * @mbggenerated
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.ROLENAME
     *
     * @param rolename the value for sys_role.ROLENAME
     *
     * @mbggenerated
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.DISABLE
     *
     * @return the value of sys_role.DISABLE
     *
     * @mbggenerated
     */
    public Integer getDisable() {
        return disable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.DISABLE
     *
     * @param disable the value for sys_role.DISABLE
     *
     * @mbggenerated
     */
    public void setDisable(Integer disable) {
        this.disable = disable;
    }
}