package com.bilibala.manage.dao.model;

public class SysUserRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.ROLEID
     *
     * @mbggenerated
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.USERID
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.ROLEID
     *
     * @return the value of sys_user_role.ROLEID
     *
     * @mbggenerated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.ROLEID
     *
     * @param roleid the value for sys_user_role.ROLEID
     *
     * @mbggenerated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.USERID
     *
     * @return the value of sys_user_role.USERID
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.USERID
     *
     * @param userid the value for sys_user_role.USERID
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }
}