package com.bilibala.manage.dao.model;

public class UserAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.USERID
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.ACCOUNTID
     *
     * @mbggenerated
     */
    private String accountid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.USERID
     *
     * @return the value of user_account.USERID
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.USERID
     *
     * @param userid the value for user_account.USERID
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.ACCOUNTID
     *
     * @return the value of user_account.ACCOUNTID
     *
     * @mbggenerated
     */
    public String getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.ACCOUNTID
     *
     * @param accountid the value for user_account.ACCOUNTID
     *
     * @mbggenerated
     */
    public void setAccountid(String accountid) {
        this.accountid = accountid == null ? null : accountid.trim();
    }
}