package com.bilibala.manage.dao.model;

import java.util.Date;

public class WxAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.ACCOUNTSCHEMA
     *
     * @mbggenerated
     */
    private String accountschema;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.APPID
     *
     * @mbggenerated
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.APPSECRET
     *
     * @mbggenerated
     */
    private String appsecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.AUTHDOMAIN
     *
     * @mbggenerated
     */
    private String authdomain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.URL
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.TOKEN
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.AESKEY
     *
     * @mbggenerated
     */
    private String aeskey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.PICURL
     *
     * @mbggenerated
     */
    private String picurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.ENABLE
     *
     * @mbggenerated
     */
    private Integer enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.CREATOR
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.CREATETIME
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.ID
     *
     * @return the value of wx_account.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.ID
     *
     * @param id the value for wx_account.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.NAME
     *
     * @return the value of wx_account.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.NAME
     *
     * @param name the value for wx_account.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.ACCOUNTSCHEMA
     *
     * @return the value of wx_account.ACCOUNTSCHEMA
     *
     * @mbggenerated
     */
    public String getAccountschema() {
        return accountschema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.ACCOUNTSCHEMA
     *
     * @param accountschema the value for wx_account.ACCOUNTSCHEMA
     *
     * @mbggenerated
     */
    public void setAccountschema(String accountschema) {
        this.accountschema = accountschema == null ? null : accountschema.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.APPID
     *
     * @return the value of wx_account.APPID
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.APPID
     *
     * @param appid the value for wx_account.APPID
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.APPSECRET
     *
     * @return the value of wx_account.APPSECRET
     *
     * @mbggenerated
     */
    public String getAppsecret() {
        return appsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.APPSECRET
     *
     * @param appsecret the value for wx_account.APPSECRET
     *
     * @mbggenerated
     */
    public void setAppsecret(String appsecret) {
        this.appsecret = appsecret == null ? null : appsecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.AUTHDOMAIN
     *
     * @return the value of wx_account.AUTHDOMAIN
     *
     * @mbggenerated
     */
    public String getAuthdomain() {
        return authdomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.AUTHDOMAIN
     *
     * @param authdomain the value for wx_account.AUTHDOMAIN
     *
     * @mbggenerated
     */
    public void setAuthdomain(String authdomain) {
        this.authdomain = authdomain == null ? null : authdomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.URL
     *
     * @return the value of wx_account.URL
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.URL
     *
     * @param url the value for wx_account.URL
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.TOKEN
     *
     * @return the value of wx_account.TOKEN
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.TOKEN
     *
     * @param token the value for wx_account.TOKEN
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.AESKEY
     *
     * @return the value of wx_account.AESKEY
     *
     * @mbggenerated
     */
    public String getAeskey() {
        return aeskey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.AESKEY
     *
     * @param aeskey the value for wx_account.AESKEY
     *
     * @mbggenerated
     */
    public void setAeskey(String aeskey) {
        this.aeskey = aeskey == null ? null : aeskey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.PICURL
     *
     * @return the value of wx_account.PICURL
     *
     * @mbggenerated
     */
    public String getPicurl() {
        return picurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.PICURL
     *
     * @param picurl the value for wx_account.PICURL
     *
     * @mbggenerated
     */
    public void setPicurl(String picurl) {
        this.picurl = picurl == null ? null : picurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.ENABLE
     *
     * @return the value of wx_account.ENABLE
     *
     * @mbggenerated
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.ENABLE
     *
     * @param enable the value for wx_account.ENABLE
     *
     * @mbggenerated
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.CREATOR
     *
     * @return the value of wx_account.CREATOR
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.CREATOR
     *
     * @param creator the value for wx_account.CREATOR
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.CREATETIME
     *
     * @return the value of wx_account.CREATETIME
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.CREATETIME
     *
     * @param createtime the value for wx_account.CREATETIME
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}