package com.bilibala.manage.dao.model;

import java.util.ArrayList;
import java.util.List;

public class WxModuleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    public WxModuleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andModuleidIsNull() {
            addCriterion("MODULEID is null");
            return (Criteria) this;
        }

        public Criteria andModuleidIsNotNull() {
            addCriterion("MODULEID is not null");
            return (Criteria) this;
        }

        public Criteria andModuleidEqualTo(String value) {
            addCriterion("MODULEID =", value, "moduleid");
            return (Criteria) this;
        }

        public Criteria andModuleidNotEqualTo(String value) {
            addCriterion("MODULEID <>", value, "moduleid");
            return (Criteria) this;
        }

        public Criteria andModuleidGreaterThan(String value) {
            addCriterion("MODULEID >", value, "moduleid");
            return (Criteria) this;
        }

        public Criteria andModuleidGreaterThanOrEqualTo(String value) {
            addCriterion("MODULEID >=", value, "moduleid");
            return (Criteria) this;
        }

        public Criteria andModuleidLessThan(String value) {
            addCriterion("MODULEID <", value, "moduleid");
            return (Criteria) this;
        }

        public Criteria andModuleidLessThanOrEqualTo(String value) {
            addCriterion("MODULEID <=", value, "moduleid");
            return (Criteria) this;
        }

        public Criteria andModuleidLike(String value) {
            addCriterion("MODULEID like", value, "moduleid");
            return (Criteria) this;
        }

        public Criteria andModuleidNotLike(String value) {
            addCriterion("MODULEID not like", value, "moduleid");
            return (Criteria) this;
        }

        public Criteria andModuleidIn(List<String> values) {
            addCriterion("MODULEID in", values, "moduleid");
            return (Criteria) this;
        }

        public Criteria andModuleidNotIn(List<String> values) {
            addCriterion("MODULEID not in", values, "moduleid");
            return (Criteria) this;
        }

        public Criteria andModuleidBetween(String value1, String value2) {
            addCriterion("MODULEID between", value1, value2, "moduleid");
            return (Criteria) this;
        }

        public Criteria andModuleidNotBetween(String value1, String value2) {
            addCriterion("MODULEID not between", value1, value2, "moduleid");
            return (Criteria) this;
        }

        public Criteria andModulenameIsNull() {
            addCriterion("MODULENAME is null");
            return (Criteria) this;
        }

        public Criteria andModulenameIsNotNull() {
            addCriterion("MODULENAME is not null");
            return (Criteria) this;
        }

        public Criteria andModulenameEqualTo(String value) {
            addCriterion("MODULENAME =", value, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameNotEqualTo(String value) {
            addCriterion("MODULENAME <>", value, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameGreaterThan(String value) {
            addCriterion("MODULENAME >", value, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameGreaterThanOrEqualTo(String value) {
            addCriterion("MODULENAME >=", value, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameLessThan(String value) {
            addCriterion("MODULENAME <", value, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameLessThanOrEqualTo(String value) {
            addCriterion("MODULENAME <=", value, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameLike(String value) {
            addCriterion("MODULENAME like", value, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameNotLike(String value) {
            addCriterion("MODULENAME not like", value, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameIn(List<String> values) {
            addCriterion("MODULENAME in", values, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameNotIn(List<String> values) {
            addCriterion("MODULENAME not in", values, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameBetween(String value1, String value2) {
            addCriterion("MODULENAME between", value1, value2, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameNotBetween(String value1, String value2) {
            addCriterion("MODULENAME not between", value1, value2, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulepathIsNull() {
            addCriterion("MODULEPATH is null");
            return (Criteria) this;
        }

        public Criteria andModulepathIsNotNull() {
            addCriterion("MODULEPATH is not null");
            return (Criteria) this;
        }

        public Criteria andModulepathEqualTo(String value) {
            addCriterion("MODULEPATH =", value, "modulepath");
            return (Criteria) this;
        }

        public Criteria andModulepathNotEqualTo(String value) {
            addCriterion("MODULEPATH <>", value, "modulepath");
            return (Criteria) this;
        }

        public Criteria andModulepathGreaterThan(String value) {
            addCriterion("MODULEPATH >", value, "modulepath");
            return (Criteria) this;
        }

        public Criteria andModulepathGreaterThanOrEqualTo(String value) {
            addCriterion("MODULEPATH >=", value, "modulepath");
            return (Criteria) this;
        }

        public Criteria andModulepathLessThan(String value) {
            addCriterion("MODULEPATH <", value, "modulepath");
            return (Criteria) this;
        }

        public Criteria andModulepathLessThanOrEqualTo(String value) {
            addCriterion("MODULEPATH <=", value, "modulepath");
            return (Criteria) this;
        }

        public Criteria andModulepathLike(String value) {
            addCriterion("MODULEPATH like", value, "modulepath");
            return (Criteria) this;
        }

        public Criteria andModulepathNotLike(String value) {
            addCriterion("MODULEPATH not like", value, "modulepath");
            return (Criteria) this;
        }

        public Criteria andModulepathIn(List<String> values) {
            addCriterion("MODULEPATH in", values, "modulepath");
            return (Criteria) this;
        }

        public Criteria andModulepathNotIn(List<String> values) {
            addCriterion("MODULEPATH not in", values, "modulepath");
            return (Criteria) this;
        }

        public Criteria andModulepathBetween(String value1, String value2) {
            addCriterion("MODULEPATH between", value1, value2, "modulepath");
            return (Criteria) this;
        }

        public Criteria andModulepathNotBetween(String value1, String value2) {
            addCriterion("MODULEPATH not between", value1, value2, "modulepath");
            return (Criteria) this;
        }

        public Criteria andModuleflagIsNull() {
            addCriterion("MODULEFLAG is null");
            return (Criteria) this;
        }

        public Criteria andModuleflagIsNotNull() {
            addCriterion("MODULEFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andModuleflagEqualTo(Integer value) {
            addCriterion("MODULEFLAG =", value, "moduleflag");
            return (Criteria) this;
        }

        public Criteria andModuleflagNotEqualTo(Integer value) {
            addCriterion("MODULEFLAG <>", value, "moduleflag");
            return (Criteria) this;
        }

        public Criteria andModuleflagGreaterThan(Integer value) {
            addCriterion("MODULEFLAG >", value, "moduleflag");
            return (Criteria) this;
        }

        public Criteria andModuleflagGreaterThanOrEqualTo(Integer value) {
            addCriterion("MODULEFLAG >=", value, "moduleflag");
            return (Criteria) this;
        }

        public Criteria andModuleflagLessThan(Integer value) {
            addCriterion("MODULEFLAG <", value, "moduleflag");
            return (Criteria) this;
        }

        public Criteria andModuleflagLessThanOrEqualTo(Integer value) {
            addCriterion("MODULEFLAG <=", value, "moduleflag");
            return (Criteria) this;
        }

        public Criteria andModuleflagIn(List<Integer> values) {
            addCriterion("MODULEFLAG in", values, "moduleflag");
            return (Criteria) this;
        }

        public Criteria andModuleflagNotIn(List<Integer> values) {
            addCriterion("MODULEFLAG not in", values, "moduleflag");
            return (Criteria) this;
        }

        public Criteria andModuleflagBetween(Integer value1, Integer value2) {
            addCriterion("MODULEFLAG between", value1, value2, "moduleflag");
            return (Criteria) this;
        }

        public Criteria andModuleflagNotBetween(Integer value1, Integer value2) {
            addCriterion("MODULEFLAG not between", value1, value2, "moduleflag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wx_module
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wx_module
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}