
CREATE USER 'wechat' IDENTIFIED BY 'wechat';

GRANT SELECT, INSERT, UPDATE, REFERENCES, DELETE, CREATE, DROP, ALTER, INDEX, TRIGGER, CREATE VIEW, SHOW VIEW, EXECUTE, ALTER ROUTINE, CREATE ROUTINE, CREATE TEMPORARY TABLES, LOCK TABLES, EVENT 
 ON `wechatmanage`.* TO 'wechat';

GRANT GRANT OPTION ON `wechatmanage`.* TO 'wechat';

GRANT SELECT, INSERT, UPDATE, REFERENCES, DELETE, CREATE, DROP, ALTER, INDEX, TRIGGER, CREATE VIEW, SHOW VIEW, EXECUTE, ALTER ROUTINE, CREATE ROUTINE, CREATE TEMPORARY TABLES, LOCK TABLES, EVENT
 ON `wechat`.* TO 'wechat';

GRANT GRANT OPTION ON `wechat`.* TO 'wechat';